### 로그인 테스트

#POST http://localhost:8080/api/login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"member1@mail.com",
  "password":"member33!@"
}

### 로그인 테스트-testDB

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"test123@gmail.com",
  "password":"12345678a!"
}

### 로그인 테스트- 서버

POST http://3.34.122.155/api/login
Content-Type: application/json

{
  "email":"member@mail.com",
  "password":"member33!@"
}



### 로그아웃 테스트
GET http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNjcxOTQ0fQ.m7UHeLgDIhOV9zdgI_bpCeeZEykxKct19TIWa3K8TfnpPqTIH86IgVdLnByNa2vM1keszTtdfMq3MeqQYWfLlg

### 로그아웃 테스트 - 서버
GET http://3.34.122.155/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNjcxOTQ0fQ.m7UHeLgDIhOV9zdgI_bpCeeZEykxKct19TIWa3K8TfnpPqTIH86IgVdLnByNa2vM1keszTtdfMq3MeqQYWfLlg

### 회원가입 테스트

#POST http://localhost:8080/api/member
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"member1@mail.com",
  "password":"member33!@",
  "name":"한글",
  "birthDate": "2002-02-10",
  "contact":"01008551213"
}

### 회원가입 테스트 - 서버

POST http://3.34.122.155/api/member
Content-Type: application/json

{
  "email":"member1@mail.com",
  "password":"member33!@",
  "name":"한글",
  "birthDate": "2002-02-10",
  "contact":"01008551213"
}

### 회원정보찾기 테스트

GET http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXIxQG1haWwuY29tIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwibWVtYmVySWQiOjExLCJleHAiOjE2MTM4NzIwNTd9.67Z22xR4sRStCRzm28iELPxneT4jpwLNzHCtoJGWdqlE8Fsjdc3lUEh9HXORCAqDBHy-ekhj1bpYOEpRHQFJXg

### 회원정보찾기 테스트 -서버

GET http://3.34.122.155/api/member/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNjcxOTk1fQ.USume4E7CrtTZ9ZJEJ0WLZPlLzmjrcQF2s0a9fZyaZi_WBLUSFxOQdN2F7TbLqWj1Icv6f0_NuFWLMzUuvJZtg


### 회원정보수정 : 메일주소

PUT http://localhost:8080/api/member/1
Content-Type: application/json

{
  "email":"member1@mail.com"

}

### 회원정보수정 : 비밀번호변경

PUT http://localhost:8080/api/member/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNTgwMDY1fQ.q6zut4omnOUtOm7RYMZOcReD_wB8ULG7LEvPxARCo6wiqJvZhgm3rWy37os-lUaTWr4O0LIeRJ9stefYXe9Gwg
Content-Type: application/json

{
  "prePassword":"member33!@",
  "password": "member33!@@"
}

### 회원삭제 테스트

DELETE http://localhost:8080/api/member/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNTQyMzEyfQ.AiJMgt4jXbX4wnD78avHe16kYu8fS9J81uaWSR2ahoexi5LW8toznmKC9BUb7TrV4HdtFHKka9-snpgB-yPBGA

### 구글로그인

### 중복회원용 회원가입
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "password":"member",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

### 회원가입 후 로그인
POST http://localhost:8080/api/login/google
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "socialId":"1234124123",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

### 구글로그인
GET http://3.34.122.155/api/login/google?code=4%2F0AY0e-g4-Yd4BWQqaWF9WlGVm8fmCAfvxh32f9yxeDlP9pakQZSr2Yn_nxzzLnVQX-lYKYQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&authuser=0&prompt=none
